title: Subleasy Documentation
baseurl: "/subleasydocs"
url: "https://csc-4330-project.github.io"
theme: minima
header_pages:
  - index.markdown
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed