title: Subleasy Documentation
baseurl: "/subleasydocs"  # Ensure this matches your repository name.
url: "https://csc-4330-project.github.io"  # This is your GitHub Pages base URL.
theme: minima

# Make sure the file exists and the name matches exactly, including the extension.
header_pages:
  - index.markdown

plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
